# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: my_theme
day_night: false
font: my_font-set
font_size: M

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: ''
phone: ''
#address: 
#  street: University of Bristol
#  city: Bristol
#  postcode: BS8 1RJ
#  country: United Kingdom
#  country_code: UK
coordinates:
  latitude: '51.45926559881649' 
  longitude: '-2.600991616247669'
#directions: Enter Building 1 and take the stairs to Office 200 on Floor 2
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
#appointment_url: 'https://calendly.com'
contact_links:
  - icon: envelope
    icon_pack: fas
    name: Email
    link: 'mailto:a.gillet@bristol.ac.uk'
  - icon: map-marker-alt
    icon_pack: fas
    name: "School of Earth Sciences<br>University of Bristol<br>Bristol, UK"
    link: 'https://www.bristol.ac.uk/earthsciences/'
#  - icon: twitter
#    icon_pack: fab
#    name: DM Me
#    link: 'https://twitter.com/Amand_Gillet'
#  - icon: skype
#    icon_pack: fab
#    name: Skype Me
#    link: 'skype:echo123?call'
#  - icon: keybase
#    icon_pack: fab
#    name: Chat on Keybase
#    link: 'https://keybase.io/'
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: 'en-us'

# Site features

highlight: true
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: 'https://github.com/gcushen/hugo-academic'
  content_dir: ''
  repo_branch: 'master'
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false   # Show estimated reading time for posts? (true/false)
section_pager: false
docs_section_pager: true  # Display pager in Docs layout (e.g. tutorials)?
sharing: true    # Enable in-built social sharing buttons? (true/false)
copyright_license:    # Show a copyright license from creativecommons.org in the site footer?  # Page specific copyright licenses are also possible by adding this option to a page's front matter.
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135    # Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
plugins_js: []
avatar:    # An avatar is an image that appears next to a user's name.   # An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
  gravatar: false
  shape: square
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: 'mapnik'
  api_key: ''
  zoom: 14
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
